import React from "react";
import dynamic from "next/dynamic";
   
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Jumbotron } from "../components/Jumbotron";
import { MenuJumbo } from "../components/MenuJumbo";
import { OrderSection } from "../components/OrderSection";
import Location from "../components/Location";
import { Yelp } from "../components/Yelp";

export default function Home() {

  return (
    <main>
      <Head>
        <title>Fat Pig BBQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Arizonia&family=Bebas+Neue&family=Courgette&family=Lobster&family=Noto+Sans&display=swap" rel="stylesheet"></link>
      </Head>
      <Jumbotron />
      <div className={styles.content}>
        <MenuJumbo />
        <OrderSection />
        <Location />
        <Yelp />
      </div>
    </main>
  );
}
