import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Jumbotron } from "../components/Jumbotron";
import { MenuJumbo } from "../components/MenuJumbo";
import { OrderSection } from "../components/OrderSection";
import Location from "../components/Location";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
<<<<<<< HEAD
        <title>Create Next App</title>
=======
        <title>Fat Pig BBQ</title>
>>>>>>> 5fff32e93329f966995f39ac6cbc8a1c0015c61e
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Jumbotron />
      <div className={styles.content}>
<<<<<<< HEAD
      <MenuJumbo />
      <OrderSection />
      </div>
      
    </div>
    
  )
=======
        <MenuJumbo />
        <OrderSection />
        <Location />
      </div>
    </div>
  );
>>>>>>> 5fff32e93329f966995f39ac6cbc8a1c0015c61e
}
