import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Jumbotron } from "../components/Jumbotron";
import { MenuJumbo } from "../components/MenuJumbo";
import { OrderSection } from "../components/OrderSection";
import Location from "../components/Location";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fat Pig BBQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Jumbotron />
      <div className={styles.content}>
        <MenuJumbo />
        <OrderSection />
        <Location />
      </div>
    </div>
  );
}
